{% set data = load_setup_py_data() %}

package:
  name: "pymt_permamodel"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - permamodel 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - permamodel 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_permamodel
  commands:
    - config_file=$(mmd-stage FrostNumber . > MANIFEST && mmd-query FrostNumber --var=run.config_file.path)
    - bmi-test pymt_permamodel.bmi:FrostNumber --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Ku . > MANIFEST && mmd-query Ku --var=run.config_file.path)
    - bmi-test pymt_permamodel.bmi:Ku --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage KuEnhanced . > MANIFEST && mmd-query KuEnhanced --var=run.config_file.path)
    - bmi-test pymt_permamodel.bmi:KuEnhanced --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the permamodel BMI.
  home: https://github.com/pymt-lab/pymt_permamodel
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_permamodel
